package com.ekuefler.supereventbus.shared;

import com.ekuefler.supereventbus.shared.impl.EventHandlerMethod;

import java.util.List;

/**
 * A tagging interface associated with classes capable of handling events. Users should declare
 * subtypes of this interface corresponding to each class that should be registered on the event bus
 * - see the documentation of {@link EventBus} for details. Implementations of this interface are
 * generated by the GWT compiler - users should NOT implement this interface themselves. This
 * interface is subject to changes which may break user-defined implementations.
 *
 * @author ekuefler@google.com (Erik Kuefler)
 * @param <T> class to which this registration applies
 */
public interface EventRegistration<T> {
  /**
   * DO NOT IMPLEMENT THIS METHOD. Implementations are generated automatically by the GWT compiler,
   * and its details are subject to change.
   */
  List<EventHandlerMethod<T, ?>> getMethods();
}
